-- Insert job roles into job_roles table (Resume_Analyzer)
-- Run in MySQL: USE Resume_Analyzer; then paste and run this block.

INSERT INTO job_roles (title, description) VALUES
('Software Engineer', NULL),
('Software Developer', NULL),
('Frontend Developer', NULL),
('Backend Developer', NULL),
('Full Stack Developer', NULL),
('Web Developer', NULL),
('Mobile App Developer', NULL),
('React Developer', NULL),
('React Native Developer', NULL),
('Flutter Developer', NULL),
('Android Developer', NULL),
('iOS Developer', NULL),
('Data Analyst', NULL),
('Data Scientist', NULL),
('Machine Learning Engineer', NULL),
('AI Engineer', NULL),
('DevOps Engineer', NULL),
('Cloud Engineer', NULL),
('QA Engineer', NULL),
('Software Tester', NULL),
('Cybersecurity Analyst', NULL),
('UI/UX Designer', NULL),
('Product Manager', NULL),
('Business Analyst', NULL),
('Project Manager', NULL),
('Operations Manager', NULL),
('HR Executive', NULL),
('Recruiter', NULL),
('Talent Acquisition Specialist', NULL),
('Accountant', NULL),
('Financial Analyst', NULL),
('Auditor', NULL),
('Digital Marketing Specialist', NULL),
('Social Media Manager', NULL),
('Content Writer', NULL),
('SEO Specialist', NULL),
('Marketing Executive', NULL),
('Sales Executive', NULL),
('Business Development Executive', NULL),
('Graphic Designer', NULL),
('Video Editor', NULL),
('Customer Support Representative', NULL),
('Administrative Assistant', NULL),
('Virtual Assistant', NULL),
('Management Trainee', NULL),
('Graduate Trainee', NULL),
('Intern', NULL),
('Junior Developer', NULL),
('Junior Analyst', NULL),
('Data Entry Specialist', NULL);
